apiVersion: v1
kind: ConfigMap
metadata:
  name: kb-config
  namespace: elk
  labels:
    k8s-app: kibana
data:
  kibana.yml: |-
    server.name: kibana
    server.host: "0"
    elasticsearch.hosts: [ "http://elasticsearch:9200" ]
    elasticsearch.requestTimeout: 180000
    elasticsearch.username: "elastic"
    elasticsearch.password: "elastic"
    xpack.monitoring.ui.container.elasticsearch.enabled: true
    i18n.locale: "zh-CN"
