apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
  namespace: elk
  labels:
    app: elasticsearch
data:
  elasticsearch.yml: |-
    #cluster.name: "docker-cluster"
    network.host: 0.0.0.0
    discovery.zen.minimum_master_nodes: 2
    #discovery.type: single-node
