apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster
  namespace: elk
spec:
  serviceName: elasticsearch-headless
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - elasticsearch
              topologyKey: "kubernetes.io/hostname"
      imagePullSecrets:
      - name: registry-secret
      containers:
      - name: elasticsearch
        image: lzzeng/es-xpack:7.5.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          tcpSocket:
            port: 9200
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 12
        readinessProbe:
          tcpSocket:
            port: 9200
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 12
        resources:
            limits:
              cpu: 1
              memory: 1500Mi
            requests:
              cpu: 0.5
              memory: 512Mi
        ports:
        - containerPort: 9200
          name: es-http
          protocol: TCP
        - containerPort: 9300
          name: cluster-port
          protocol: TCP

        env:
          - name: REQUESTS_MEMORY
            valueFrom:
              resourceFieldRef:
                resource: requests.memory
                divisor: 1Mi
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name

          - name: cluster.name
            value: es-cluster
          - name: http.cors.enabled
            value: "true"
          - name: http.cors.allow-origin
            value: "*"
          - name: ELASTIC_PASSWORD
            value: "elastic"
          - name: ES_JAVA_OPTS
            value: "-Xms$(REQUESTS_MEMORY)m -Xmx$(REQUESTS_MEMORY)m"
          - name: cluster.initial_master_nodes
            value: "es-cluster-0,es-cluster-1,es-cluster-2"
          - name: discovery.seed_hosts
            value: "es-cluster-0.elasticsearch-headless,es-cluster-1.elasticsearch-headless,es-cluster-2.elasticsearch-headless"

        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data-elasticsearch

        - name: config
          subPath: elasticsearch.yml
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml

      initContainers:
      - name: vm-max-map
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: fd-ulimit
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "ulimit -n 65535"]
        securityContext:
          privileged: true

      volumes:
      - name: config
        configMap:
          name: es-config

  volumeClaimTemplates:
  - metadata:
      name: data-elasticsearch
    spec:
      storageClassName: "managed-nfs-storage"
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 8Gi
