apiVersion: v1
kind: ConfigMap
metadata:
  name: kb-config
  namespace: elk
  labels:
    app: kibana
data:
  kibana.yml: |-
    server.name: kibana
    server.host: "0"
    # elasticsearch.url: "http://elasticsearch:9200"
    # elasticsearch.hosts: ["http://es-cluster-0.elasticsearch.elk:9200", "http://es-cluster-1.elasticsearch.elk:9200", "http://es-cluster-2.elasticsearch.elk:9200"]
    elasticsearch.hosts: ["http://es-cluster-0.elasticsearch-headless.elk:9200", "http://es-cluster-1.elasticsearch-headless.elk:9200", "http://es-cluster-2.elasticsearch-headless.elk:9200"]
    elasticsearch.requestTimeout: 180000
    elasticsearch.username: "elastic"
    elasticsearch.password: "elastic"
    xpack.monitoring.ui.container.elasticsearch.enabled: true
    i18n.locale: "zh-CN"
